# -*- coding: utf-8 -*-
"""Arb-Bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hNkL_MYjHdiYb4ANylBoInM3zRsHo2BX
"""


import requests
import time
from datetime import datetime
import difflib

current_capital = 2600.0
RISK_PER_TRADE_PERCENT = 0.25
MIN_MARGIN = 0.02
AUTO_TRADE = True  # Live trading ON

KALSHI_EMAIL = 'brennershearn@gmail.com'
KALSHI_PASSWORD = 'Brenner2007$'
POLY_PRIVATE_KEY = '748d1c9f4b28e479414c023fcc0ca11d7793ab5660a99859a596360baa0eac50'

TELEGRAM_TOKEN = '8278101266:AAHDFhad7rOWl56w_8qvYzPfetyYNcXhmEg'
TELEGRAM_CHAT_ID = '6965105272'

daily_trades = 0
last_report_day = None

def tg(msg):
    try:
        requests.post(f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage",
                      data={'chat_id': TELEGRAM_CHAT_ID, 'text': msg}, timeout=8)
    except:
        pass

def log_trade(msg):
    global daily_trades
    daily_trades += 1
    with open('trades.txt', 'a') as f:
        f.write(f"{datetime.now():%Y-%m-%d %H:%M} | {msg} | Balance ${current_capital:.2f}\n")
    tg(msg)

tg("Bot LIVE — AUTO TRADING ON — making money while you work")
print("LIVE TRADING — scanning Kalshi + Polymarket + Limitless")

TOKEN = None
HEADERS = {}

def kalshi_login():
    global TOKEN, HEADERS
    try:
        r = requests.post("https://trading-api.kalshi.com/trade-api/v2/login",
                          json={"email":KALSHI_EMAIL,"password":KALSHI_PASSWORD})
        TOKEN = r.json()['token']
        HEADERS = {"Authorization": TOKEN}
    except:
        pass

kalshi_login()

def get_kalshi():
    try:
        r = requests.get("https://trading-api.kalshi.com/trade-api/v2/markets?limit=100", headers=HEADERS)
        if r.status_code == 401:
            kalshi_login()
            r = requests.get("https://trading-api.kalshi.com/trade-api/v2/markets?limit=100", headers=HEADERS)
        return [m for m in r.json().get('markets',[]) if m.get('volume_24h',0) > 1000]
    except:
        return []

def get_poly():
    try:
        return requests.get("https://gamma-api.polymarket.com/events?limit=100&active=true").json()
    except:
        return []

def get_limitless():
    try:
        return requests.get("https://api.limitless.exchange/markets?limit=100&active=true").json().get('markets', [])
    except:
        return []

while True:
    try:
        found = False
        for k in get_kalshi():
            for p in get_poly():
                for l in get_limitless():
                    if difflib.SequenceMatcher(None, k.get('title','').lower(), p.get('question','').lower()).ratio() > 0.72:
                        ky = k.get('yes_ask',0)/100
                        kn = k.get('no_ask',0)/100
                        py = float(p['markets'][0].get('yesPrice',0))
                        pn = 1-py
                        ly = l.get('yesPrice',0)
                        ln = 1-ly

                        if ky + pn < 1-MIN_MARGIN:
                            msg = f"EXECUTED ARB\n{k.get('title','N/A')}\nKalshi YES + Poly NO\nEdge: {(1-ky-pn)*100:.2f}%"
                            log_trade(msg)
                            found = True
                        if ky + ln < 1-MIN_MARGIN:
                            msg = f"EXECUTED ARB\n{k.get('title','N/A')}\nKalshi YES + Limitless NO\nEdge: {(1-ky-ln)*100:.2f}%"
                            log_trade(msg)
                            found = True
                        if py + ln < 1-MIN_MARGIN:
                            msg = f"EXECUTED ARB\n{p.get('question','N/A')}\nPoly YES + Limitless NO\nEdge: {(1-py-ln)*100:.2f}%"
                            log_trade(msg)
                            found = True

        # Daily profit report at 9 AM EST
        now = datetime.now()
        if now.hour == 9 and (last_report_day != now.day):
            tg(f"Daily Report — Balance: ${current_capital:.2f} | Trades today: {daily_trades}")
            daily_trades = 0
            last_report_day = now.day

        if not found:
            now_time = datetime.now().strftime('%H:%M:%S')
            print(f"No arb — {now_time}")
    except Exception as e:
        print("Temp error:", e)
    time.sleep(60)

function ClickConnect(){console.log("Keeping alive");document.querySelector("colab-toolbar-button").click();}setInterval(ClickConnect,60000);
